name: Generate and Publish Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '55 * * * *'
    - cron: '25 * * * *'

jobs:
  job_home:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.12'
      - run: python -m pip install -r requirements.txt
      - run: python spaghetti.py home 45.7256 12.6897
      - uses: actions/upload-artifact@v3
        with:
          name: home-output
          path: ./output/home

  job_cs:
    runs-on: ubuntu-latest
    needs: job_home
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.12'
      - run: python -m pip install -r requirements.txt
      - run: python spaghetti.py cs 45.7585 12.8447
      - uses: actions/upload-artifact@v3
        with:
          name: cs-output
          path: ./output/cs

  job_rugby:
    runs-on: ubuntu-latest
    needs: job_cs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.12'
      - run: python -m pip install -r requirements.txt
      - run: python spaghetti.py rugby 45.6956 12.7102
      - uses: actions/upload-artifact@v3
        with:
          name: rugby-output
          path: ./output/rugby

  deploy:
    runs-on: ubuntu-latest
    needs: [job_home, job_cs, job_rugby]
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: home-output
          path: ./output/home
      - uses: actions/download-artifact@v3
        with:
          name: cs-output
          path: ./output/cs
      - uses: actions/download-artifact@v3
        with:
          name: rugby-output
          path: ./output/rugby
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          keep_files: true
